# Generated by Django 4.2.13 on 2024-06-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Сategory',
        ),
    ]
