# Generated by Django 4.2.13 on 2024-06-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_category_сategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сategory',
            new_name='Category',
        ),
    ]
